### ISSUE TITLE
Pipx produces errors when trying to install the wrapper

### ISSUE THREAD

**Issue by fcnjd** [mmabrouk/chatgpt-wrapper#314] opened 2023-06-23 15:39 UTC
**Describe the bug**
Something in the installation process or a dependency is broken. I don't beleive it is a pipx error itself, because in the past I already installed the wrapper the very same way.

**To Reproduce**
1: If not yet present, install pipx.
2: If not yet present, add an SSH key to github.
3: As a normal user, execute the following line:
pipx install git+ssh://git@github.com/mmabrouk/chatgpt-wrapper --verbose
4: If prompted, enter the passphrase for the SSH keys, that may happen several times.
5: Find the below error stacktrace.

**Expected behavior**
The installation should work, just as usual.

**Additional context**
Here's the traceback of the error I'm getting.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/packaging/_parser.py", line 206, in _parse_specifier
    with tokenizer.enclosing_tokens("LEFT_PARENTHESIS", "RIGHT_PARENTHESIS"):
  File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/packaging/_tokenizer.py", line 183, in enclosing_tokens
    self.raise_syntax_error(
  File "/usr/lib/python3/dist-packages/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    extract-msg (<=0.29.*)
                ~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 819, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 202, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/commands/install.py", line 60, in install
    venv.install_package(
  File "/usr/lib/python3/dist-packages/pipx/venv.py", line 244, in install_package
    self._update_package_metadata(
  File "/usr/lib/python3/dist-packages/pipx/venv.py", line 318, in _update_package_metadata
    venv_package_metadata = self.get_venv_metadata_for_package(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/venv.py", line 300, in get_venv_metadata_for_package
    venv_metadata = inspect_venv(
                    ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/venv_inspect.py", line 251, in inspect_venv
    app_paths_of_dependencies = _dfs_package_apps(
                                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/venv_inspect.py", line 142, in _dfs_package_apps
    app_paths_of_dependencies = _dfs_package_apps(
                                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/venv_inspect.py", line 121, in _dfs_package_apps
    dependencies = get_package_dependencies(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/venv_inspect.py", line 54, in get_package_dependencies
    for req in map(Requirement, dist.requires or []):
  File "/usr/lib/python3/dist-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    extract-msg (<=0.29.*)

**Comment by thehunmonkgroup** [comment] 2023-06-24 21:16
```
pipdeptree -r -p extract-msg
extract-msg==0.28.7
└── textract==1.6.5 [requires: extract-msg<=0.29.*]
    └── chatGPT==0.12.2 [requires: textract]
```
As you can see, the `textract` package is the one requiring `extract-msg`.

I suggest you try to reproduce the error by installing `textract` directly, and if so, file an issue with the `textract` project.

**Comment by thehunmonkgroup** [comment] 2023-06-24 21:18
Closing, duplicate of #312

**Closed by thehunmonkgroup** 2023-06-24 21:18 UTC

**Comment by thehunmonkgroup** [comment] 2023-06-25 15:19
Sadly, textract isn't being well-maintained, and there's no other good general use extraction package I could find.

So, I rolled a custom version of the package to fix the issue.

Installing the newest version of this package should now work: https://github.com/mmabrouk/chatgpt-wrapper/releases/tag/v0.12.3

**Comment by fcnjd** [comment] 2023-06-29 20:59
Thank you very much for your efforts in building this workaround. Now everything works as expected again.

**Comment by thehunmonkgroup** [comment] 2023-06-29 21:40
Glad to hear it!
