### ISSUE TITLE
TypeError: 'async for'   v0.4.1

### ISSUE THREAD

**Issue by liaoxingjian** [mmabrouk/chatgpt-wrapper#186] opened 2023-03-01 09:26 UTC
Hi, I have installed the latest version. But there was a problem running the following code:

from chatgpt_wrapper import ChatGPT
bot = ChatGPT()
response = bot.ask("Hello, world!")
print(response)

Traceback (most recent call last):
  File "/Users/lxj/PyRespository/chatGPT_test/main.py", line 4, in <module>
    response = bot.ask("Hello, world!")
  File "/opt/homebrew/Caskroom/miniforge/base/envs/chat/lib/python3.8/site-packages/chatgpt_wrapper/chatgpt.py", line 503, in ask
    return asyncio.run(super().ask(message))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/chat/lib/python3.8/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/chat/lib/python3.8/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/chat/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniforge/base/envs/chat/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/chat/lib/python3.8/site-packages/chatgpt_wrapper/chatgpt.py", line 463, in ask
    response = list([i async for i in self.ask_stream(message)])
TypeError: 'async for' requires an object with __aiter__ method, got generator

**Comment by Mrw33554432** [comment] 2023-03-01 10:12
Same

**Comment by matt-ewan-laws** [comment] 2023-03-01 12:52
I'm getting this problem too on first gen M1 and ubuntu 20.04. Works on a later version of ubuntu

**Comment by thehunmonkgroup** [comment] 2023-03-01 15:53
Duplicate of #185

**Closed by thehunmonkgroup** 2023-03-01 15:53 UTC
