### ISSUE TITLE
How to use multiple accounts in parrellal 

### ISSUE THREAD

**Issue by waterhorse1** [mmabrouk/chatgpt-wrapper#241] opened 2023-03-19 23:55 UTC
I wonder how to use multiple account in parrellal for chatgpt-wrapper, currently when I try to call chatgpt install for my second account in a new terminal, it will ask me to close the previous firefox. How to solve it?

**Comment by thehunmonkgroup** [comment] 2023-03-20 01:29
Duplicate of #236

**Comment by thehunmonkgroup** [comment] 2023-03-20 01:32
You can run multiple instances of the wrapper with the same account, multiple accounts are not currently supported, but I would consider a PR that implemented this cleanly -- that may not be easy to do.

**Closed** 2023-03-20 12:00 UTC
