### ISSUE TITLE
Immediate traceback after providing a prompt to ChatGPT after it hasn't been used in a while

### ISSUE THREAD

**Issue by jaybird110127** [mmabrouk/chatgpt-wrapper#67] opened 2023-01-20 08:12 UTC
I'm on Windows 10. After not having used the Chatgpt program for a while (several hours) when I first run it and provide a prompt, I get an immediate traceback, as follows:

Provide a prompt for ChatGPT, or type !help or ? to list commands.
1> What is a dog?
Traceback (most recent call last):
  File "C:\python39\Scripts\chatgpt-script.py", line 33, in <module>
    sys.exit(load_entry_point('chatGPT==0.3.8', 'console_scripts', 'chatgpt')())
  File "C:\python39\lib\site-packages\chatgpt-0.3.8-py3.9.egg\chatgpt_wrapper\chatgpt.py", line 570
, in main
  File "C:\python39\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\python39\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "C:\python39\lib\site-packages\chatgpt-0.3.8-py3.9.egg\chatgpt_wrapper\chatgpt.py", line 365
, in do_ask
  File "C:\python39\lib\site-packages\chatgpt-0.3.8-py3.9.egg\chatgpt_wrapper\chatgpt.py", line 372
, in default
  File "C:\python39\lib\site-packages\chatgpt-0.3.8-py3.9.egg\chatgpt_wrapper\chatgpt.py", line 107
, in ask_stream
  File "C:\python39\lib\site-packages\chatgpt-0.3.8-py3.9.egg\chatgpt_wrapper\chatgpt.py", line 72,
 in refresh_session
  File "C:\python39\lib\site-packages\playwright\sync_api\_generated.py", line 7697, in evaluate
    self._sync(
  File "C:\python39\lib\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
  File "C:\python39\lib\site-packages\playwright\_impl\_page.py", line 407, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "C:\python39\lib\site-packages\playwright\_impl\_frame.py", line 277, in evaluate
    await self._channel.send(
  File "C:\python39\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "C:\python39\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "C:\python39\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation

**Comment by zk1009** [comment] 2023-02-24 05:11
I meet the same problem, have you solved it yet?

**Comment by mmabrouk** [comment] 2023-02-27 10:25
Running !session should solve the problem. The problem should have been fixed in #153 
Please let me know if the issue is still there

**Closed by mmabrouk** 2023-02-27 10:25 UTC
Labels: windows
