### ISSUE TITLE
issue during docker build

### ISSUE THREAD

**Issue by vgren** [mmabrouk/chatgpt-wrapper#279] opened 2023-04-07 07:54 UTC
#12 2.341 Installed /usr/lib/python3.8/site-packages/chatGPT-0.8.2-py3.8.egg
#12 2.346 Processing dependencies for chatGPT==0.8.2
#12 3.381 error: SQLAlchemy 2.0.9 is installed but SQLAlchemy<2,>=1 is required by {'langchain'

**Comment by thehunmonkgroup** [comment] 2023-04-07 12:58
Can you try editing the last line of the `Dockerfile` from this:

```
RUN python setup.py install
```
to this:
```
RUN pip install -e .
```
Re-run and see if that fixes the issue?

**Comment by vgren** [comment] 2023-04-07 17:56
thanks @thehunmonkgroup , it kinda helped but docker logs of container show this:

`----- Please follow these steps -----
1) Run command `docker exec -it chatgpt-wrapper-container /bin/bash -c \"chatgpt\"`
2) Follow the instructions to create the first user
3) Have a nice chat
Traceback (most recent call last):
  File "chatgpt_wrapper/gpt_api.py", line 5, in <module>
    from chatgpt_wrapper.backends.openai.api import OpenAIAPI
ModuleNotFoundError: No module named 'chatgpt_wrapper'

----- Please follow these steps -----
1) Run command `docker exec -it chatgpt-wrapper-container /bin/bash -c \"chatgpt\"`
2) Follow the instructions to create the first user
3) Have a nice chat
Traceback (most recent call last):
  File "chatgpt_wrapper/gpt_api.py", line 5, in <module>
    from chatgpt_wrapper.backends.openai.api import OpenAIAPI
ModuleNotFoundError: No module named 'chatgpt_wrapper'`

**Comment by thehunmonkgroup** [comment] 2023-04-07 20:53
Duplicate of #276

**Closed by thehunmonkgroup** 2023-04-07 20:53 UTC
