### ISSUE TITLE
`NotImplementedError` error 

### ISSUE THREAD

**Issue by karliell** [mmabrouk/chatgpt-wrapper#228] opened 2023-03-15 20:39 UTC
I got this error when running the python chatgpt example on the website:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[4], line 3
      1 from chatgpt_wrapper import ChatGPT
----> 3 bot = ChatGPT()
      4 success, response, message = bot.ask("Hello, world!")
      5 if success:

File c:\users\chatgpt-wrapper\chatgpt_wrapper\chatgpt.py:485, in ChatGPT.__init__(self, config, timeout, proxy)
    483 self.log = Logger(self.__class__.__name__, self.config)
    484 self.agpt = AsyncChatGPT(config)
--> 485 self.async_run(self.agpt.create(timeout, proxy))

File c:\users\chatgpt-wrapper\chatgpt_wrapper\chatgpt.py:494, in ChatGPT.async_run(self, awaitable)
    493 def async_run(self, awaitable):
--> 494     return asyncio.get_event_loop().run_until_complete(awaitable)

File ~\Anaconda3\envs\env\lib\site-packages\nest_asyncio.py:90, in _patch_loop.<locals>.run_until_complete(self, future)
     87 if not f.done():
     88     raise RuntimeError(
     89         'Event loop stopped before Future completed.')
---> 90 return f.result()

File ~\Anaconda3\envs\env\lib\asyncio\futures.py:178, in Future.result(self)
    176 self.__log_traceback = False
    177 if self._exception is not None:
--> 178     raise self._exception
    179 return self._result

File ~\Anaconda3\envs\env\lib\asyncio\tasks.py:280, in Task.__step(***failed resolving arguments***)
    276 try:
    277     if exc is None:
    278         # We use the `send` method directly, because coroutines
    279         # don't have `__iter__` and `__next__` methods.
--> 280         result = coro.send(None)
    281     else:
    282         result = coro.throw(exc)

File c:\users\chatgpt-wrapper\chatgpt_wrapper\chatgpt.py:46, in AsyncChatGPT.create(self, timeout, proxy)
     44 self.streaming = False
     45 self.lock = asyncio.Lock()
---> 46 self.play = await async_playwright().start()
     47 browser = self.config.get('browser.provider')
     48 headless = not self.config.get('browser.debug')

File ~\Anaconda3\envs\env\lib\site-packages\playwright\async_api\_context_manager.py:51, in PlaywrightContextManager.start(self)
     50 async def start(self) -> AsyncPlaywright:
---> 51     return await self.__aenter__()

File ~\Anaconda3\envs\env\lib\site-packages\playwright\async_api\_context_manager.py:46, in PlaywrightContextManager.__aenter__(self)
     44 if not playwright_future.done():
     45     playwright_future.cancel()
---> 46 playwright = AsyncPlaywright(next(iter(done)).result())
     47 playwright.stop = self.__aexit__  # type: ignore
     48 return playwright

File ~\Anaconda3\envs\env\lib\asyncio\futures.py:178, in Future.result(self)
    176 self.__log_traceback = False
    177 if self._exception is not None:
--> 178     raise self._exception
    179 return self._result

File ~\Anaconda3\envs\env\lib\asyncio\tasks.py:280, in Task.__step(***failed resolving arguments***)
    276 try:
    277     if exc is None:
    278         # We use the `send` method directly, because coroutines
    279         # don't have `__iter__` and `__next__` methods.
--> 280         result = coro.send(None)
    281     else:
    282         result = coro.throw(exc)

File ~\Anaconda3\envs\env\lib\site-packages\playwright\_impl\_connection.py:247, in Connection.run(self)
    244 async def init() -> None:
    245     self.playwright_future.set_result(await self._root_object.initialize())
--> 247 await self._transport.connect()
    248 self._init_task = self._loop.create_task(init())
    249 await self._transport.run()

File ~\Anaconda3\envs\env\lib\site-packages\playwright\_impl\_transport.py:127, in PipeTransport.connect(self)
    125 except Exception as exc:
    126     self.on_error_future.set_exception(exc)
--> 127     raise exc
    129 self._output = self._proc.stdin

File ~\Anaconda3\envs\env\lib\site-packages\playwright\_impl\_transport.py:116, in PipeTransport.connect(self)
    113     if getattr(sys, "frozen", False):
    114         env.setdefault("PLAYWRIGHT_BROWSERS_PATH", "0")
--> 116     self._proc = await asyncio.create_subprocess_exec(
    117         str(self._driver_executable),
    118         "run-driver",
    119         stdin=asyncio.subprocess.PIPE,
    120         stdout=asyncio.subprocess.PIPE,
    121         stderr=_get_stderr_fileno(),
    122         limit=32768,
    123         env=env,
    124     )
    125 except Exception as exc:
    126     self.on_error_future.set_exception(exc)

File ~\Anaconda3\envs\env\lib\asyncio\subprocess.py:236, in create_subprocess_exec(program, stdin, stdout, stderr, loop, limit, *args, **kwds)
    229     warnings.warn("The loop argument is deprecated since Python 3.8 "
    230                   "and scheduled for removal in Python 3.10.",
    231                   DeprecationWarning,
    232                   stacklevel=2
    233     )
    234 protocol_factory = lambda: SubprocessStreamProtocol(limit=limit,
    235                                                     loop=loop)
--> 236 transport, protocol = await loop.subprocess_exec(
    237     protocol_factory,
    238     program, *args,
    239     stdin=stdin, stdout=stdout,
    240     stderr=stderr, **kwds)
    241 return Process(transport, protocol, loop)

File ~\Anaconda3\envs\env\lib\asyncio\base_events.py:1630, in BaseEventLoop.subprocess_exec(self, protocol_factory, program, stdin, stdout, stderr, universal_newlines, shell, bufsize, encoding, errors, text, *args, **kwargs)
   1628     debug_log = f'execute program {program!r}'
   1629     self._log_subprocess(debug_log, stdin, stdout, stderr)
-> 1630 transport = await self._make_subprocess_transport(
   1631     protocol, popen_args, False, stdin, stdout, stderr,
   1632     bufsize, **kwargs)
   1633 if self._debug and debug_log is not None:
   1634     logger.info('%s: %r', debug_log, transport)

File ~\Anaconda3\envs\env\lib\asyncio\base_events.py:491, in BaseEventLoop._make_subprocess_transport(self, protocol, args, shell, stdin, stdout, stderr, bufsize, extra, **kwargs)
    487 async def _make_subprocess_transport(self, protocol, args, shell,
    488                                      stdin, stdout, stderr, bufsize,
    489                                      extra=None, **kwargs):
    490     """Create subprocess transport."""
--> 491     raise NotImplementedError

NotImplementedError: 
```

**Comment by thehunmonkgroup** [comment] 2023-03-16 00:01
It doesn't appear that you're using the latest version of the wrapper. Please upgrade to the latest version and try to reproduce.

**Comment by thehunmonkgroup** [comment] 2023-03-16 00:02
It's this line that tippped me off, we removed this module dependency:

```
File ~\Anaconda3\envs\env\lib\site-packages\nest_asyncio.py:90
```

**Comment by karliell** [comment] 2023-03-16 01:48
> It doesn't appear that you're using the latest version of the wrapper. Please upgrade to the latest version and try to reproduce.

sorry, may i ask how to upgrade? upgrade which library.

**Comment by karliell** [comment] 2023-03-16 01:53
> It's this line that tippped me off, we removed this module dependency:
> 
> ```
> File ~\Anaconda3\envs\env\lib\site-packages\nest_asyncio.py:90
> ```

I have this code:
```
!pip install nest_asyncio
import nest_asyncio
nest_asyncio.apply()
```

Otherwise, i got this error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 6
      4 config = Config()
      5 config.set('browser.debug', False)
----> 6 bot = ChatGPT(config)
      7 success, response, message = bot.ask("Who is Alanson Sample in Umich?")
      8 if success:

File ~/Documents/chatgpt-wrapper/chatgpt_wrapper/chatgpt.py:485, in ChatGPT.__init__(self, config, timeout, proxy)
    483 self.log = Logger(self.__class__.__name__, self.config)
    484 self.agpt = AsyncChatGPT(config)
--> 485 self.async_run(self.agpt.create(timeout, proxy))

File ~/Documents/chatgpt-wrapper/chatgpt_wrapper/chatgpt.py:494, in ChatGPT.async_run(self, awaitable)
    493 def async_run(self, awaitable):
--> 494     return asyncio.get_event_loop().run_until_complete(awaitable)

File ~/miniforge3/envs/env/lib/python3.9/asyncio/base_events.py:623, in BaseEventLoop.run_until_complete(self, future)
    612 """Run until the Future is done.
    613 
    614 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    620 Return the Future's result, or raise its exception.
    621 """
    622 self._check_closed()
--> 623 self._check_running()
    625 new_task = not futures.isfuture(future)
    626 future = tasks.ensure_future(future, loop=self)

File ~/miniforge3/envs/env/lib/python3.9/asyncio/base_events.py:583, in BaseEventLoop._check_running(self)
    581 def _check_running(self):
    582     if self.is_running():
--> 583         raise RuntimeError('This event loop is already running')
    584     if events._get_running_loop() is not None:
    585         raise RuntimeError(
    586             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running
```

**Comment by karliell** [comment] 2023-03-16 18:02
> Do you get this error when running the test script at https://github.com/mmabrouk/chatgpt-wrapper/blob/main/tests/test_sync_chatgpt.py ?

yes

**Comment by thehunmonkgroup** [comment] 2023-03-16 19:15
I cannot reproduce, the test script is working fine in my environment.

What environment are you running it in? I'm talking about running the test script from a standard shell, not from inside some other process or library or framework.

**Comment by thehunmonkgroup** [comment] 2023-03-16 22:43
https://github.com/mmabrouk/chatgpt-wrapper/commit/f7c62860b8825d0485566d0d05c3c76ff927f93a might fix the `RuntimeError: This event loop is already running` error, please upgrade to latest code by uninstalling and reinstalling the module, and test.

**Comment by karliell** [comment] 2023-03-19 17:39
got similar error:
```
---------------------------------------------------------------------------
InvalidStateError                         Traceback (most recent call last)
Cell In[1], line 3
      1 from chatgpt_wrapper import ChatGPT
----> 3 bot = ChatGPT()
      4 success, response, message = bot.ask("Hello, world!")
      5 if success:

File c:\users\documents\chatgpt-wrapper\chatgpt_wrapper\chatgpt.py:494, in ChatGPT.__init__(self, config, timeout, proxy)
    492 self.log = Logger(self.__class__.__name__, self.config)
    493 self.agpt = AsyncChatGPT(config)
--> 494 self.async_run(self.agpt.create(timeout, proxy))

File c:\users\documents\chatgpt-wrapper\chatgpt_wrapper\chatgpt.py:506, in ChatGPT.async_run(self, awaitable)
    504 if loop.is_running():
    505     future = asyncio.ensure_future(awaitable)
--> 506     return future.result()
    507 else:
    508     return loop.run_until_complete(awaitable)

InvalidStateError: Result is not set.

Task exception was never retrieved
future: <Task finished name='Task-5' coro=<Connection.run() done, defined at C:\Users\yaxuanli\Anaconda3\envs\env\lib\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\env\lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "C:\Users\Anaconda3\envs\env\lib\site-packages\playwright\_impl\_transport.py", line 127, in connect
    raise exc
  File "C:\Users\Anaconda3\envs\env\lib\site-packages\playwright\_impl\_transport.py", line 116, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Anaconda3\envs\env\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Anaconda3\envs\env\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Anaconda3\envs\env\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```
If you are available, we can have a zoom call to let you use my computer. Thank you so much!

**Comment by thehunmonkgroup** [comment] 2023-03-19 18:20
I'm not spending any more time on this issue.

My limited research on `asyncio` suggests that poor design makes a sync call to an already running event loop difficult: https://stackoverflow.com/a/56662635

The change I committed at https://github.com/mmabrouk/chatgpt-wrapper/commit/88b8e5bb91edadc67082e29c8f76f2ba0fb9ec54 *may* help, but it may not.

As I said before, I cannot reproduce this issue in my environment, so it's likely the issue is particular to the environment in which the module is being used. If this is the case, you have other options:

1. Use the async class instead of the sync class
2. Use the API backend instead of the browser backend (may help, not sure, but it will take `playwright` out of the picture, which is using the event loop, too.)
3. Hire somebody to help you figure out your edge case.

**Comment by thehunmonkgroup** [comment] 2023-04-01 20:24
Async functionality has been removed, which I think makes this issue moot.

**Closed by thehunmonkgroup** 2023-04-01 20:24 UTC
