### ISSUE TITLE
Flask API is broken 

### ISSUE THREAD

**Issue by thelastpolaris** [mmabrouk/chatgpt-wrapper#194] opened 2023-03-01 17:42 UTC
I get the following error when trying to query GET /conversations

```
[2023-03-01 23:39:24,924] ERROR in app: Exception on /conversations [POST]
Traceback (most recent call last):
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/polaris/dev/bplan/chatgpt-api/chatgpt-wrapper/chatgpt_wrapper/gpt_api.py", line 32, in ask
    result = chatgpt.ask(prompt)
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/chatgpt_wrapper/chatgpt.py", line 520, in ask
    return asyncio.run(self.agpt.ask(message))
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/chatgpt_wrapper/chatgpt.py", line 476, in ask
    response = list([i async for i in self.ask_stream(message)])
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/chatgpt_wrapper/chatgpt.py", line 476, in <listcomp>
    response = list([i async for i in self.ask_stream(message)])
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/chatgpt_wrapper/chatgpt.py", line 305, in ask_stream
    await self.refresh_session()
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/chatgpt_wrapper/chatgpt.py", line 136, in refresh_session
    await self.page.goto("https://chat.openai.com/api/auth/session")
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 9162, in goto
    await self._impl_obj.goto(
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/playwright/_impl/_page.py", line 494, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/Users/polaris/dev/bplan/chatgpt-api/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 70, in inner_send
    done, _ = await asyncio.wait(
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 411, in wait
    fs = {ensure_future(f, loop=loop) for f in fs}
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 411, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in fs}
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 671, in ensure_future
    raise ValueError('The future belongs to a different loop than '
ValueError: The future belongs to a different loop than the one specified as the loop argument
192.168.0.103 - - [01/Mar/2023 23:39:24] "POST /conversations HTTP/1.1" 500 -
```

**Comment by thehunmonkgroup** [comment] 2023-03-01 18:22
Duplicate of #191

**Closed by thehunmonkgroup** 2023-03-01 18:22 UTC
