### ISSUE TITLE
!history and set_title stopped working

### ISSUE THREAD

**Issue by mmabrouk** [mmabrouk/chatgpt-wrapper#133] opened 2023-02-22 18:16 UTC
It appears that both the !history and set_title commands have stopped functioning as of today. It's possible that there has been a change in their internal API that has caused this problem. Previously, the implementation would raise an exception if set_title failed, but I have now modified it to log a debug text instead.

Unfortunately, when attempting to use the !history command, an error was returned. As a temporary solution, I have disabled the command for now. I apologize for any poorly written fixes as I am pressed for time in the upcoming weeks.

2> !history
INFO:root:Failed to get history: 403 Forbidden {'date': 'Wed, 22 Feb 2023 18:09:57 GMT', 'content-type': 'text/html; charset=UTF-8', 'transfer-encoding': 'chunked', 'connection': 'close', 'permissions-policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()', 'x-frame-options': 'SAMEORIGIN', 'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'vary': 'Accept-Encoding', 'cross-origin-opener-policy': 'same-origin', 'referrer-policy': 'same-origin', 'x-robots-tag': 'nofollow', 'server': 'cloudflare', 'cf-ray': '79d9ad00cba2ac9e-TXL', 'content-encoding': 'br', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}
Traceback (most recent call last):
File "/Users/mahmoudmabrouk/opt/anaconda3/bin/chatgpt", line 33, in
sys.exit(load_entry_point('chatGPT', 'console_scripts', 'chatgpt')())
File "/Users/mahmoudmabrouk/code/chatgpt_wrapper/chatgpt_wrapper/main.py", line 79, in main
shell.cmdloop()
File "/Users/mahmoudmabrouk/opt/anaconda3/lib/python3.9/cmd.py", line 138, in cmdloop
stop = self.onecmd(line)
File "/Users/mahmoudmabrouk/opt/anaconda3/lib/python3.9/cmd.py", line 217, in onecmd
return func(arg)
File "/Users/mahmoudmabrouk/code/chatgpt_wrapper/chatgpt_wrapper/gpt_shell.py", line 107, in do_history
self._print_markdown("## Recent history:\n\n%s" % "\n".join(["1. %s: %s (%s)" % (datetime.datetime.strptime(h['create_time'], "%Y-%m-%dT%H:%M:%S.%f").strftime("%Y-%m-%d %H:%M"), h['title'], h['id']) for h in history['items']]))
TypeError: 'NoneType' object is not subscriptable

**Comment by thehunmonkgroup** [comment] 2023-02-22 18:41
I cannot reproduce the issues with `!history/!title`, see #132.

The original error code was (hilariously) partially written by ChatGPT, and was never working. I do have a fix for that in a pending PR, but I can push a change shortly that adjusts your hotfix. I think we should still throw here, just provide more/better info if we can.

**Comment by mmabrouk** [comment] 2023-02-23 11:33
I kept encountering the same problem. Please note that the error occurs after receiving a response from ChatGPT, which makes authentication issues unlikely. I finally solved the problem by removing /tmp/playwright and using the install mode.

The current code raises an exception with the error message attached below. Instead, I suggest printing an error message and handling the error gracefully, without stopping the code's execution. Especially since neither set_title nor history are the core feature of the cli. This approach will make the code more resilient to errors, especially if OpenAI makes breaking changes. It will also allow users to continue using the CLI even if such changes occur and we're unable to react in time.

What do you think?

`Exception: Failed to set title: 403 Forbidden {'date': 'Thu, 23 Feb 2023 11:23:39 GMT', 'content-type': 'text/html; charset=UTF-8', 'transfer-encoding': 'chunked', 'connection': 'close', 'permissions-policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()', 'x-frame-options': 'SAMEORIGIN', 'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'set-cookie': '__cf_bm=QS46TIfjteTE7_FazcneQMMaO6dEHKv6u2LANLiJ_Hk-1677151419-0-ASPWgiGKdWwsr3AEIqm+5lPDJgUjSSzCe5Q+rOhJtEnY9IEgDlA8FaaGJzZgl3jNUkCjWQvmpgetJk1hlvG60FY=; path=/; expires=Thu, 23-Feb-23 11:53:39 GMT; domain=.chat.openai.com; HttpOnly; Secure; SameSite=None', 'vary': 'Accept-Encoding', 'cross-origin-opener-policy': 'same-origin', 'referrer-policy': 'same-origin', 'x-robots-tag': 'nofollow', 'server': 'cloudflare', 'cf-ray': '79df9735387aac9e-TXL', 'content-encoding': 'br', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}`

**Comment by mmabrouk** [comment] 2023-02-23 11:46
ok, now I have again the issue. I will reapply the hotfix of printing a warning instead until we understand the problem

**Comment by thehunmonkgroup** [comment] 2023-02-23 13:13
Curious if you get the same error for `!history` when manually entering the GET request in the browser with `--debug` enabled?

Another thought: are they doing something different based on geolocation?

**Comment by mmabrouk** [comment] 2023-02-23 13:30
!history works fine. The code also works fine with --debug, actually it seems after running --debug, set_title start working again. Very weird bug

**Comment by thehunmonkgroup** [comment] 2023-02-23 16:12
OK, I took the time to implement a bit more robust logging functionality, see https://github.com/mmabrouk/chatgpt-wrapper/commit/fed870fbb40d68bb92179cf3b4fa51736e559b6e

Still need to add more logging statements, but I believe this handles the errors you reported above in a more robust way, and also positions the code to have better long-term debugging facilities.

**Comment by thehunmonkgroup** [comment] 2023-02-23 21:30
Today I too ran into an issue with `!history` not working, but only for a bit.

It's entirely possible these are transient errors due to adjustments on OpenAI's end.

As of this moment, with the latest fixes implemented, everything is working for me, and with the latest code, if either `!history`, `!delete` or the call to `_set_title()` fails, you should get an error message, but no crash.

**Comment by thehunmonkgroup** [comment] 2023-02-23 21:32
I'm going to close this for now, as all indications are that the issues are transitory, and we now have better error handling to prevent crashes in this case.

If these issues start happening again globally and consistently, we can reopen to debug further.

**Closed by thehunmonkgroup** 2023-02-23 21:32 UTC

**Comment by gyliu513** [comment] 2023-02-23 21:43
@thehunmonkgroup I was using the latest code, but still got the exception for each prompt, can you help? Thanks!

```console
guangyaliu@Guangyas-MacBook-Pro-2 chatgpt-wrapper % git pull
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 8 (delta 6), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (8/8), 1.08 KiB | 100.00 KiB/s, done.
From https://github.com/mmabrouk/chatgpt-wrapper
   5e77169..c1c44f9  main       -> origin/main
Updating 5e77169..c1c44f9
Fast-forward
 chatgpt_wrapper/chatgpt.py   | 40 +++++++++++++++++++++++++---------------
 chatgpt_wrapper/gpt_shell.py | 15 ++++++++-------
 2 files changed, 33 insertions(+), 22 deletions(-)
```
```console
guangyaliu@Guangyas-MacBook-Pro-2 chatgpt-wrapper % pip3 install git+https://github.com/mmabrouk/chatgpt-wrapper
Collecting git+https://github.com/mmabrouk/chatgpt-wrapper
  Cloning https://github.com/mmabrouk/chatgpt-wrapper to /private/var/folders/wp/mnb1wbtd7gq0wxf12dvy49f40000gn/T/pip-req-build-4_ym3z86
  Running command git clone --filter=blob:none --quiet https://github.com/mmabrouk/chatgpt-wrapper /private/var/folders/wp/mnb1wbtd7gq0wxf12dvy49f40000gn/T/pip-req-build-4_ym3z86
  Resolved https://github.com/mmabrouk/chatgpt-wrapper to commit c1c44f9ff65cb21331ddf0abe59246db241b17f8
  Preparing metadata (setup.py) ... done
Requirement already satisfied: playwright in /usr/local/lib/python3.11/site-packages (from chatGPT==0.3.17) (1.31.0)
Requirement already satisfied: rich in /usr/local/lib/python3.11/site-packages (from chatGPT==0.3.17) (13.3.1)
Requirement already satisfied: greenlet==2.0.1 in /usr/local/lib/python3.11/site-packages (from playwright->chatGPT==0.3.17) (2.0.1)
Requirement already satisfied: pyee==9.0.4 in /usr/local/lib/python3.11/site-packages (from playwright->chatGPT==0.3.17) (9.0.4)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/site-packages (from pyee==9.0.4->playwright->chatGPT==0.3.17) (4.5.0)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.1.0 in /usr/local/lib/python3.11/site-packages (from rich->chatGPT==0.3.17) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.14.0 in /usr/local/lib/python3.11/site-packages (from rich->chatGPT==0.3.17) (2.14.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/site-packages (from markdown-it-py<3.0.0,>=2.1.0->rich->chatGPT==0.3.17) (0.1.2)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
```
```console
guangyaliu@Guangyas-MacBook-Pro-2 chatgpt-wrapper % playwright install firefox
```
```console
guangyaliu@Guangyas-MacBook-Pro-2 chatgpt-wrapper % chatgpt install
Install mode: Log in to ChatGPT in the browser that pops up, and click
through all the dialogs, etc. Once that is achieved, exit and restart
this program without the 'install' parameter.

Provide a prompt for ChatGPT, or type !help or ? to list commands.
1> chatgpt what is one plus one

The sum of one plus one is equal to two (2).Traceback (most recent call last):
  File "/usr/local/bin/chatgpt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/main.py", line 79, in main
    shell.cmdloop()
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/cmd.py", line 217, in onecmd
    return func(arg)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/gpt_shell.py", line 148, in do_ask
    return self.default(line)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/gpt_shell.py", line 157, in default
    for chunk in self.chatgpt.ask_stream(line):
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/chatgpt.py", line 303, in ask_stream
    self._set_title()
  File "/usr/local/lib/python3.11/site-packages/chatgpt_wrapper/chatgpt.py", line 149, in _set_title
    raise Exception(f"Failed to set title: {response.status} {response.status_text} {response.headers}")
Exception: Failed to set title: 403 Forbidden {'date': 'Thu, 23 Feb 2023 21:41:24 GMT', 'content-type': 'text/html; charset=UTF-8', 'transfer-encoding': 'chunked', 'connection': 'close', 'permissions-policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()', 'x-frame-options': 'SAMEORIGIN', 'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'vary': 'Accept-Encoding', 'cross-origin-opener-policy': 'same-origin', 'referrer-policy': 'same-origin', 'x-robots-tag': 'nofollow', 'server': 'cloudflare', 'cf-ray': '79e3201df8a72d22-IAD', 'content-encoding': 'br', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}
```

**Comment by thehunmonkgroup** [comment] 2023-02-24 02:22
Not really sure what you're doing there, but you're definitely not running the latest code, we're not throwing `Exception` for that error any more.

You may want to investigate installing this package in development mode if you want to run on the bleeding edge.

**Comment by thehunmonkgroup** [comment] 2023-02-24 15:08
If you've experienced this issue, it would be extremely helpful if you could offer more information to the developers about your setup, see the bottom of the original issue post at #142 for more info
